sudo: required
services:
    - docker
before_install:
    - docker build -t dolgan12/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true dolgan12/react-test npm test
after_success:
    - docker build -t dolgan12/multi-client ./client
    - docker build -t dolgan12/multi-nginx ./nginx
    - docker build -t dolgan12/multi-server ./server
    - docker build -t dolgan12/multi-worker ./worker
    # Login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # Take those images and push them to docker hub.
    - docker push dolgan12/multi-client
    - docker push dolgan12/multi-nginx
    - docker push dolgan12/multi-server
    - docker push dolgan12/multi-worker